services:
  easyconvert-cli:
    build: .
    container_name: easyconvert-cli
    depends_on:
      - redis
    environment:
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - CACHE_DB=${CACHE_DB}
    command: >
      /bin/sh -c "
        echo 'Starting app...' &&
        echo 'Redis host: ${CACHE_HOST}, port: ${CACHE_PORT}' &&
        easyconvert cache-status &&
        easyconvert cache-clear &&
        easyconvert roman X &&
        easyconvert roman X &&
        easyconvert arabic 234 &&
        easyconvert cache-keys &&

        echo 'Done!'
      "

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis2:
    image: redis:latest
    container_name: redis2
    restart: unless-stopped
    ports:
      - "6378:6379"
    volumes:
      - redis_data2:/data
    command: ["redis-server", "--appendonly", "yes"]


volumes:
  redis_data:
  redis_data2: